version: 2
jobs:
  build:
    working_directory: ~/micropost
    docker:
      - image: circleci/php:7.3.9-apache-buster
        environment:
          APP_ENV: test
          DATABASE_URL: mysql://kg:dupa.tam@127.0.0.1:3306/micro-post
          MAILER_URL: smtp://82f41431fc8029:fdcf7a6746105d@smtp.mailtrap.io:25
          MAILER_FROM: micro@micropost.com
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: kg
          MYSQL_PASSWORD: dupa.tam
          MYSQL_DATABASE: micro-post
    steps:
      - checkout
      - run:
          name: Install apt
          command: sudo apt install -y zlib1g-dev
      - run:
          name: Create empty .env file, required by Symfony
          command: touch .env
      - run:
          name: Install PHP MySQL
          command: sudo docker-php-ext-install pdo_mysql zip
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Composer
          command: sudo composer self-update
      - run:
          name: Composer install
          command: composer install -n --prefer-dist
      - run:
          name: Run migrations
          command: php bin/console doctrine:migrations:migrate --env=test --no-interaction
      - run:
          name: Run tests
          command: php bin/phpunit
  deploy:
    working_directory: ~/micropost
    docker:
      - image: circleci/php:7.3.9-apache-buster
        environment:
          APP_ENV: prod
          DATABASE_URL: mysql://kg:dupa.tam@127.0.0.1:3306/micro-post
          MAILER_URL: smtp://82f41431fc8029:fdcf7a6746105d@smtp.mailtrap.io:25
          MAILER_FROM: micro@micropost.com
      - image: circleci/node:9.11.2
    steps:
      - checkout
      - run:
          name: Create empty .env file, required by Symfony
          command: touch .env
      - run:
          name: Composer install
          command: composer install -n --prefer-dist
      - run:
          name: Clear cache
          command: php bin/console cache:clear --env=prod --no-interaction
      - run:
          name: Yarn
          command: yarn install && yarn run encore production
      - run:
          name: Add droplet
          command: ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
      - run:
          name: Pre-deploy
          command: ssh -T $DROPLET_USER:$DROPLET_IP < bin/deploy/pre_deploy.sh
      - run:
          name: Deploy code
          command: rsync -vzcrSLhp --delete ~/micropost/ $DROPLET_USER@DROPLET_IP:/var/www/micropost_current
      - run:
          name: Post deploy
          command: ssh -T $DROPLET_USER:$DROPLET_IP < bin/deploy/deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

